/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    BlockingExplanation: typeof import('./src/components/BlockingExplanation.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CompositePolicyBuilder: typeof import('./src/components/CompositePolicyBuilder.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    JustificationTreeView: typeof import('./src/components/JustificationTreeView.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    PolicyRuleCard: typeof import('./src/components/PolicyRuleCard.vue')['default']
    PolicyWorkspace: typeof import('./src/components/PolicyWorkspace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SimulatorInspector: typeof import('./src/components/SimulatorInspector.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Tree: typeof import('primevue/tree')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
